# Generated by Django 4.2.4 on 2023-09-02 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
