# Generated by Django 4.2.4 on 2023-11-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='cABC',
        ),
    ]
