# Generated by Django 4.2.4 on 2023-11-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_content_comment_cabc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cABC',
            new_name='comment',
        ),
    ]
